create table tb_task (cost float(53), limit_date date, id bigint generated by default as identity, order_apresentation bigint, name varchar(255) unique, primary key (id));
create table tb_task (cost float(53), limit_date date, id bigint generated by default as identity, order_apresentation bigint, name varchar(255) unique, primary key (id));
